receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  # loki:
  #   endpoint: https://loki:3100/loki/api/v1/push"
  #   tenant_id: "example1"

extensions:
  health_check:
  pprof:
  zpages:
  # basicauth/prw:
  #   client_auth:
  #     username: admin
  #     password: admin

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
